name: Deploy a Static Website to S3 Using GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: static-website-github
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ env.AWS_REGION }}

      - name: Creating S3 bucket and ignore if it already exists
        run: |
          aws s3api create-bucket \
            --bucket $BUCKET_NAME \
            --region $AWS_REGION \
            --create-bucket-cofiguration LocationConstraint=$AWS_REGION || echo "Bucket may already exist"
                        
      - name: Enabling Static Website Hosting
        run: |
          aws s3 website s3://$BUCKET_NAME/ \
            --index-document index.html 

      - name: Set Public Bucket Policy
        run: | 
          POLICY=$(cat <<EOF
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Sid": "PublicReadGetObject",
                        "Effect": "Allow",
                        "Principal": "*",
                        "Action": "s3:GetObject",
                        "Resource": "arn:aws:s3:::$BUCKET_NAME/*"
                    }
                ]
            }
          EOF
          )

          echo "$POLICY" > bucket-policy.json
          aws s2api put-bucket-policy --bucket $BUCKET_NAME --policy file://bucket-policy.json

      - name: Uploading Website Files
        run: |
           aws se3 sync s3://$BUCKET_NAME --delete --exclude ".git/*"

      - name: Website URL
        run: | 
          echo "Website URL: http://$BUCKET_NAME.s3-website-$AWS_REGION.amazonaws.com "
