name: Deploy a Static Website to S3 Using GitHub Actions

on:
  push:
    branches:
      - 
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: static-website-github
      AWS-REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ env.AWS_REGION }}

      - name: Creating S3 bucket and ignore if it already exists
        run: |
          aws s3api create-bucket \
            --bucket $BUCKET_NAME \
            --region $AWS_REGION \
            --create-bucket-cofiguration LocationConstraint=$AWS_REGION || echo "Bucket may already exist"
                        
      - name: Enabling Static Website Hosting
        run: |
          aws s3 website s3://$BUCKET_NAME/ \
            --index-document index.html 

      - name: Set Public Bucket Policy
          
